using Test
using DiscreteGlobalGrids

# Separate suite modules prevent same-named system exports from colliding.
@testset "DiscreteGlobalGrids.jl" begin
    include("raster_selection.jl")
    include("raster_geometry_regressions.jl")
    include("query_frontier.jl")
    include("rasterize.jl")
    include("raster_extract_zonal.jl")
    include("partitioning/runtests.jl")
    include("partitioning/backends.jl")
    include("partitioning/distributed.jl")
    include("interface/runtests.jl")
    include("fallbacks/runtests.jl")
    include("fallbacks/authalic.jl")
    include("systems/IGeo7/runtests.jl")
    include("systems/H3/runtests.jl")
    include("systems/HEALPix/runtests.jl")
    include("systems/A5/runtests.jl")
    include("systems/S2/runtests.jl")
    include("systems/ISEA4R/runtests.jl")
    # CopernicusDEM needs its own sweep because `systems()` omits it.
    include("systems/CopernicusDEM/runtests.jl")
    include("systems/crosssystem/runtests.jl")
    include("systems/crosssystem/cell_corners.jl")
    # Multi-order suites share the committed California outline fixture.
    include("systems/crosssystem/multiorder_polygons.jl")
    include("systems/crosssystem/multiorder_budget.jl")
    include("systems/crosssystem/cell_vector.jl")
    include("systems/crosssystem/multiorder_vector.jl")
    include("systems/crosssystem/aggregate.jl")
    include("systems/crosssystem/multiorder_data.jl")
    include("systems/crosssystem/multiorder_grid.jl")
    include("systems/crosssystem/subtree_iterators.jl")
    include("systems/crosssystem/stencils.jl")
    include("systems/crosssystem/neighborhood.jl")
    include("systems/crosssystem/mapneighbors.jl")
    include("systems/crosssystem/needs.jl")
    include("systems/crosssystem/subtree_halos.jl")
    include("systems/crosssystem/region_algebra.jl")
    include("systems/crosssystem/dimensionaldata.jl")
    include("systems/crosssystem/regridding_conservation.jl")
    include("systems/crosssystem/regrid.jl")
    include("systems/crosssystem/regrid_dual.jl")
    include("systems/crosssystem/regrid_acceptance.jl")
    include("io/runtests.jl")
    include("plotting/runtests.jl")
    include("scripts/copdem_source_mode.jl")
    include("scripts/copdem_policy.jl")
    include("raster_rasters_ext.jl")
    include("raster_api_regressions.jl")
end
