name = "DiscreteGlobalGrids"
uuid = "443be784-8f3c-41ab-9ff0-108bddc7e690"
version = "0.1.0"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
ConservativeRegridding = "8e50ac2c-eb48-49bc-a402-07c87b949343"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
GeometryOpsCore = "05efe853-fabf-41c8-927e-7063c8b9f013"
H3_jll = "60c8821e-da38-5dbd-93c7-983f1e6d69be"
Healpix = "9f4e344d-96bc-545a-84a3-ae6b9e1b672b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[sources.ConservativeRegridding]
path = "../ConservativeRegridding.jl"

[sources.GeometryOps]
rev = "ng-port"
url = "https://github.com/JuliaGeo/GeometryOps.jl.git"

[sources.GeometryOpsCore]
rev = "ng-port"
subdir = "GeometryOpsCore"
url = "https://github.com/JuliaGeo/GeometryOps.jl.git"

[compat]
Healpix = "4"
julia = "1.11"
